### ISSUE TITLE
可不可做一个推送功能，把当前经纬度推送到用户设定的地址

### ISSUE THREAD

**Issue by worker1024** [andych008/AMapDemo#1]
如题

**Comment by andych008** [comment]
- 这个项目的描述：“高德定位简单封装”。
- 这个项目的目标：降低使用高德定位的难度，能够覆盖安卓开发的常见使用场景，提高高德定位的易用性。

如果有后续开发，我只会增加高德定位相关的功能。应该不会有推送相关的东西。
